### ISSUE TITLE
Non-Issue - No issues found with Micron's submission checker

### ISSUE THREAD

**Issue by wvaske** [mlcommons/hn7st6jxx77dbthjf9co#5]
I developed a submission checker that I've shared here: https://github.com/wvaske/mlps_submission_checker

There were no issues found in the submission. Here is the verbose output (lists non-issues for each check) with the performance report at the end.

```
[root@wvaske-lg01 ~/github/hn7st6jxx77dbthjf9co 3136]# check_mlps_submission.py -r . -a -s huawei -v
Processing 7 submitters...
Processing 3 Reports and 15 Summaries
Running Check: check_inter_test_times
Running Check: check_file_system_caching
Running Check: check_checkpoint_files_in_code
Running Check: check_num_epochs
Running Check: check_reports_exist
Running Check: check_dataset_size
Checking submitter dataset size: Huawei

Submitter: Huawei
  NON-ISSUE: time_between_runs_exceeds_avg_runtime
    Report: ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_31_hosts
      Details:
        deltas: 176, 176, 1692, 669
        run_times: 1449, 1451, 1447, 1447, 1483
        aus: 96.12%, 96.04%, 96.13%, 96.06%, 93.91%
        au_std: 0.9746
    Report: ./Huawei/Huawei_0820/Open/Huawei/results/OceanStor_A800_with_LSPC_56_hosts
      Details:
        deltas: 119, 1182, 2899, 1121
        run_times: 1300, 1300, 1298, 1297, 1304
        aus: 91.28%, 91.26%, 91.33%, 91.31%, 91.17%
        au_std: 0.062

  NON-ISSUE: minimal_time_between_runs
    Report: ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_51_hosts
      Details:
        deltas: 189, 188, 190, 189
        run_times: 1183, 1198, 1190, 1184, 1186
        aus: 92.22%, 91.24%, 91.39%, 92.01%, 91.87%
        au_std: 0.4161

  NON-ISSUE: no_cached_runs
    Report: ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_31_hosts
      Details:
        cached_percents: 0.53%, 0.53%, 0.53%, 0.53%, 0.54%
        file_cache_size (MiB): 1,022; 1,024; 1,020; 1,025; 1,022
        aus: 96.12%, 96.04%, 96.13%, 96.06%, 93.91%
        au_std: 0.9746
    Report: ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_51_hosts
      Details:
        cached_percents: 0.52%, 0.51%, 0.51%, 0.52%, 0.53%
        file_cache_size (MiB): 989; 983; 986; 989; 1,007
        aus: 92.22%, 91.24%, 91.39%, 92.01%, 91.87%
        au_std: 0.4161
    Report: ./Huawei/Huawei_0820/Open/Huawei/results/OceanStor_A800_with_LSPC_56_hosts
      Details:
        cached_percents: 0.53%, 0.54%, 0.53%, 0.53%, 0.55%
        file_cache_size (MiB): 1,021; 1,028; 1,020; 1,018; 1,046
        aus: 91.28%, 91.26%, 91.33%, 91.31%, 91.17%
        au_std: 0.062

  NON-ISSUE: checkpoint_files_not_in_code
    Report: 
      Details:
        checkpoint_files: []

  NON-ISSUE: runs_are_5_epochs
    Report: ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_31_hosts
      Details:
        epochs: [5, 5, 5, 5, 5]
    Report: ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_51_hosts
      Details:
        epochs: [5, 5, 5, 5, 5]
    Report: ./Huawei/Huawei_0820/Open/Huawei/results/OceanStor_A800_with_LSPC_56_hosts
      Details:
        epochs: [5, 5, 5, 5, 5]

  NON-ISSUE: All summaries have a generated report
    Report: 
      Details:
        summaries_with_reports: ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_31_hosts/unet3d-h100/run1/host1/summary.json
                                ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_31_hosts/unet3d-h100/run2/host1/summary.json
                                ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_31_hosts/unet3d-h100/run3/host1/summary.json
                                ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_31_hosts/unet3d-h100/run4/host1/summary.json
                                ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_31_hosts/unet3d-h100/run5/host1/summary.json
                                ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_51_hosts/unet3d-h100/run1/host1/summary.json
                                ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_51_hosts/unet3d-h100/run2/host1/summary.json
                                ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_51_hosts/unet3d-h100/run3/host1/summary.json
                                ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_51_hosts/unet3d-h100/run4/host1/summary.json
                                ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_51_hosts/unet3d-h100/run5/host1/summary.json
                                ./Huawei/Huawei_0820/Open/Huawei/results/OceanStor_A800_with_LSPC_56_hosts/unet3d-h100/run1/host1/summary.json
                                ./Huawei/Huawei_0820/Open/Huawei/results/OceanStor_A800_with_LSPC_56_hosts/unet3d-h100/run2/host1/summary.json
                                ./Huawei/Huawei_0820/Open/Huawei/results/OceanStor_A800_with_LSPC_56_hosts/unet3d-h100/run3/host1/summary.json
                                ./Huawei/Huawei_0820/Open/Huawei/results/OceanStor_A800_with_LSPC_56_hosts/unet3d-h100/run4/host1/summary.json
                                ./Huawei/Huawei_0820/Open/Huawei/results/OceanStor_A800_with_LSPC_56_hosts/unet3d-h100/run5/host1/summary.json

  NON-ISSUE: dataset_larger_than_necessary
    Report: ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_31_hosts
      Details:
        workload: unet3d
        accelerator: h100
        num_accelerators: 155
        num_hosts: 31
        client_host_memory_in_gb: 185
        datasize_minimums: [542500, 542500, 542500, 542500, 542500]
        num_files_train: [840000, 840000, 840000, 840000, 840000]
        train_as_percent_of_requirement: [154.8, 154.8, 154.8, 154.8, 154.8]

  NON-ISSUE: correct_dataset_size
    Report: ./Huawei/Huawei_0820/Closed/Huawei/results/OceanStor_A800_51_hosts
      Details:
        workload: unet3d
        accelerator: h100
        num_accelerators: 255
        num_hosts: 51
        client_host_memory_in_gb: 187
        datasize_minimums: [892500, 892500, 892500, 892500, 892500]
        num_files_train: [910000, 910000, 910000, 910000, 910000]
        train_as_percent_of_requirement: [102.0, 102.0, 102.0, 102.0, 102.0]
    Report: ./Huawei/Huawei_0820/Open/Huawei/results/OceanStor_A800_with_LSPC_56_hosts
      Details:
        workload: unet3d
        accelerator: h100
        num_accelerators: 392
        num_hosts: 56
        client_host_memory_in_gb: 187
        datasize_minimums: [1372000, 1372000, 1372000, 1372000, 1372000]
        num_files_train: [1396500, 1396500, 1396500, 1396500, 1396500]
        train_as_percent_of_requirement: [101.8, 101.8, 101.8, 101.8, 101.8]


```

Let me know if there are questions on any of this output. Again, just documenting that I found no issues.
